language: go

go:
  - 1.6

install:
  - sudo add-apt-repository -y ppa:masterminds/glide
  - sudo apt-get update
  - sudo apt-get install glide
  - make bootstrap

script:
  - make cc

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
  - "target/json-flatten-linux-amd64"
  - "target/json-flatten-darwin-amd64"
  skip_cleanup: true
  on:
    tags: true
